import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import AppBar from "./components/Appbar";
import RecoidContextProvider from "./recoilContextProvider";

const inter = Inter({ subsets: ["latin"] });
const dm_sans = DM_Sans({
  subsets:['latin'],
  weight:['300','400','500'],
  variable:'--font-dm_sans',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={`${inter.className} ${dm_sans.className}`}>
        <AppBar></AppBar>
        <RecoidContextProvider>{children}</RecoidContextProvider>
      </body>
    </html>
  );
}
